name: Pre-commit Pipeline
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - name: Setup java JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Run UTs, FTs and build with Maven
        run: ./mvnw clean install


